#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _; \n\trewrite ^\/redirect_me https:\/\/github.com\/Reeny12 permanent;"

sudo sed -i "s/servername _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
