#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "This script needs to be run with root privileges to display listening ports."
  exit 1
fi

listening_ports=$(netstat -tuln | grep 'LISTEN')

echo "PID   Port   Program"

while read -r line; do

  port=$(echo "$line" | awk '{print $4}')
  protocol=$(echo "$line" | awk '{print $1}')

  pid=$(lsof -i "$protocol:$port" | grep 'LISTEN' | awk '{print $2}')

  program=$(ps -p "$pid" -o comm=)

  echo "$pid   $port   $program"
done <<< "$listening_ports"

